version: '3.4'

services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      -  "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  dockerapientity:
    image: ${DOCKER_REGISTRY-}dockerapientity
    container_name: project_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80" 
    depends_on:
      - db


 
